version: '3.9'

services: 
  app:
    image: java-clm-app:latest
    build:
      context: .
    environment:
      # required
      NEW_RELIC_LICENSE_KEY: $NEW_RELIC_LICENSE_KEY
      # optional
      NEW_RELIC_HOST: ${NEW_RELIC_HOST:-}
    ports:
      - 127.0.0.1:8080:8080
    # stdin_open: true
    # tty: true
    volumes:
      - "./logs:/app/logs"
